version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: SolutionDev-app
    ports:
      - 9090:9090
    volumes:
      - ./:/try/backend

  db:
    container_name: SolutionDev-db
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
      MYSQL_USER: "mysql"
      MYSQL_PASSWORD: "mysql"
      MYSQL_DATABASE: "develop"
    volumes:
      - db-store:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  db-store: